# Generated by Django 4.2.7 on 2023-12-01 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppDigestoVillaNueva', '0003_documento_creado_por_documento_modificado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
