# Generated by Django 4.2.7 on 2023-12-01 14:18

import AppDigestoVillaNueva.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDigestoVillaNueva', '0006_resolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaracion',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppDigestoVillaNueva.documento')),
                ('numero_declaracion', models.PositiveIntegerField(default=1)),
                ('anio', models.IntegerField(default=2023)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to=AppDigestoVillaNueva.models.upload_to_declaracion, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='ERROR, el archivo tiene que estar en formato PDF.')])),
            ],
            bases=('AppDigestoVillaNueva.documento',),
        ),
    ]
