# Generated by Django 4.2.7 on 2023-12-04 14:11

import AppDigestoVillaNueva.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppDigestoVillaNueva', '0007_declaracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletinOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('decretos', models.BooleanField(default=False)),
                ('resoluciones', models.BooleanField(default=False)),
                ('ordenanzas', models.BooleanField(default=False)),
                ('declaraciones', models.BooleanField(default=False)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to=AppDigestoVillaNueva.models.upload_to_boletin)),
            ],
        ),
    ]
